### PR TITLE
Change triplet errors to a tuple format

### PR DESCRIPTION
**Pull request by davecaos**
With this the `key` field will be like  `#{key => resolver_crash, ...}` instead of returning `#{key => {resolver_crash, <<"PlanningSuggestions">>, <<"phrases">>, ...},`

### CODE REVIEW

**Comment by davecaos** [comment]
Changelog updated ❗️ 
log-lady-story

**Comment by gausby** [comment]
Cool, if it is a breaking change I don't know if it should be a `0.10` instead of `0.9.1`. We are still in pre-1.0, so I don't know if it maters that much.

**Comment by jlouis** [comment]
This should have been merged into develop for `0.11.0`, but I've bumped the version number so that part I've omitted. The "only one error per path" branch has not been merged in.

**Comment by jlouis** [comment]
I think this one can be closed. The important patch is slated for inclusion in the next release.

**Comment by jlouis** [comment]
Also: who the hell is the fine lady with a log in this PR?

**Comment by mortenbo** [comment]
> Also: who the hell is the fine lady with a log in this PR?

I think she's the perfect visual representation of a protected branch.

**Comment by jlouis** [comment]
Can we close this one? I believe it has been resolved through other merges.

The "One Error Per Path" problem mentioned warrants its own PR I think, going forward.

**Comment by davecaos** [comment]
Yes, it was solved in a previous commit.
closed ❗️

**Pull request closed without merging**
